namespace RepoManager.Infrastructure.Persistence.SeedData;

public static class ReleaseNotesTemplateBody
{
    public const string Default = """
        <ac:structured-macro ac:name="info">
          <ac:rich-text-body>
            <p>Released on <strong>{{formatDate releaseDate "MMMM dd, yyyy"}}</strong> · Version <strong>{{version}}</strong></p>
          </ac:rich-text-body>
        </ac:structured-macro>

        {{#if tickets.breaking}}
        <h2>Breaking Changes</h2>
        <ul>
          {{#each tickets.breaking}}
          <li><strong>{{key}}</strong> — {{summary}}</li>
          {{/each}}
        </ul>
        {{/if}}

        {{#if tickets.features}}
        <h2>New Features</h2>
        <ul>
          {{#each tickets.features}}
          <li><strong>{{key}}</strong> — {{summary}}</li>
          {{/each}}
        </ul>
        {{/if}}

        {{#if tickets.fixes}}
        <h2>Bug Fixes</h2>
        <ul>
          {{#each tickets.fixes}}
          <li><strong>{{key}}</strong> — {{summary}}</li>
          {{/each}}
        </ul>
        {{/if}}

        {{#if tickets.other}}
        <h2>Other Changes</h2>
        <ul>
          {{#each tickets.other}}
          <li><strong>{{key}}</strong> — {{summary}}</li>
          {{/each}}
        </ul>
        {{/if}}

        <h2>Repositories</h2>
        <table>
          <thead>
            <tr>
              <th>Repository</th>
              <th>Previous Version</th>
              <th>Next Version</th>
              <th>Commits</th>
            </tr>
          </thead>
          <tbody>
            {{#each repositories}}
            <tr>
              <td><strong>{{name}}</strong></td>
              <td><code>{{previousVersion}}</code></td>
              <td><code>{{nextVersion}}</code></td>
              <td>{{commitCount}}</td>
            </tr>
            {{/each}}
          </tbody>
        </table>

        <p><em>Generated by Release Manager · {{formatDate releaseDate "yyyy-MM-dd HH:mm"}} UTC</em></p>
        """;
}
