namespace RepoManager.Infrastructure.Persistence.SeedData;

public static class ReleaseSummaryTemplateBody
{
    public const string Default = """
        <ac:structured-macro ac:name="info">
          <ac:rich-text-body>
            <p>Released on <strong>{{formatDate releaseDate "MMMM dd, yyyy"}}</strong></p>
          </ac:rich-text-body>
        </ac:structured-macro>

        <table>
          <thead>
            <tr>
              <th>Repository</th>
              <th>Service Owner</th>
              <th>Previous Version</th>
              <th>Next Version</th>
              <th>Commits</th>
              <th>Tickets</th>
            </tr>
          </thead>
          <tbody>
            {{#each repositories}}
            <tr>
              <td><strong>{{name}}</strong></td>
              <td>{{#if serviceOwner}}{{serviceOwner}}{{else}}—{{/if}}</td>
              <td><code>{{previousVersion}}</code></td>
              <td><code>{{nextVersion}}</code></td>
              <td>{{commitCount}}</td>
              <td>{{ticketCount}}</td>
            </tr>
            {{/each}}
          </tbody>
        </table>

        <p><em>Generated by Release Manager · {{formatDate releaseDate "yyyy-MM-dd HH:mm"}} UTC</em></p>
        """;
}
