using FluentAssertions;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using RepoManager.Application.Confluence;
using RepoManager.Application.DTOs.Releases;
using RepoManager.Domain.Entities;
using RepoManager.Domain.Enums;
using RepoManager.Infrastructure.Persistence;
using RepoManager.Infrastructure.Releases;
using RepoManager.Infrastructure.Services.Handlebars;

namespace RepoManager.IntegrationTests.Bindings;

/// <summary>
/// Verifies the AddProjectTemplateBindings migration backfill SQL:
/// - Creates exactly one ReleaseNotes binding per project with a non-null ReleaseNoteTemplateId.
/// - Skips projects whose ReleaseNoteTemplateId is NULL.
/// - After migration, PrepareAsync renders titles matching the pre-upgrade template for each project.
/// </summary>
public class BindingMigrationTests : IDisposable
{
    // Exact backfill SQL copied from AddProjectTemplateBindings.Up() — must stay in sync.
    private const string BackfillSql = @"
INSERT INTO TemplateBindings (
    Id, ProjectId, TemplateId, Kind,
    PageTitleTemplate, ParentPageId,
    LinkFromReleaseNotes, SortOrder,
    CreatedAt, UpdatedAt)
SELECT
    lower(hex(randomblob(4))) || '-' ||
    lower(hex(randomblob(2))) || '-4' ||
    lower(substr(hex(randomblob(2)), 2)) || '-9' ||
    lower(substr(hex(randomblob(2)), 2)) || '-' ||
    lower(hex(randomblob(6))),
    Id,
    ReleaseNoteTemplateId,
    'ReleaseNotes',
    '{{project.name}} {{version}} — Release Notes',
    NULL,
    0,
    0,
    CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER),
    CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)
FROM Projects
WHERE ReleaseNoteTemplateId IS NOT NULL;";

    private readonly SqliteConnection _connection;

    public BindingMigrationTests()
    {
        _connection = new SqliteConnection("Data Source=:memory:");
        _connection.Open();
        CreatePreMigrationSchema();
    }

    public void Dispose() => _connection.Dispose();

    // ── Backfill: single project with template ────────────────────────────────

    [Fact]
    public void Backfill_ProjectWithTemplate_CreatesOneReleaseNotesBinding()
    {
        var templateId = SeedTemplate();
        var projectId = SeedProject(templateId);

        ExecuteBackfill();

        var bindings = GetAllBindings();
        bindings.Should().HaveCount(1);
        var b = bindings[0];
        b.ProjectId.Should().Be(projectId.ToString());
        b.TemplateId.Should().Be(templateId.ToString());
        b.Kind.Should().Be("ReleaseNotes");
        b.PageTitleTemplate.Should().Be("{{project.name}} {{version}} — Release Notes",
            "the migration must use the standard pre-upgrade title template with an em dash");
        b.SortOrder.Should().Be(0);
        b.LinkFromReleaseNotes.Should().Be(0, "default is false");
        b.ParentPageId.Should().BeNull();
    }

    [Fact]
    public void Backfill_ProjectWithoutTemplate_CreatesNoBinding()
    {
        SeedProject(null);

        ExecuteBackfill();

        CountBindings().Should().Be(0,
            "projects with null ReleaseNoteTemplateId must not receive a backfill binding");
    }

    [Fact]
    public void Backfill_MixedProjects_CreatesOneBindingPerTemplatedProject()
    {
        var t1 = SeedTemplate("Template A");
        var t2 = SeedTemplate("Template B");
        var p1 = SeedProject(t1);
        var p2 = SeedProject(t2);
        _ = SeedProject(null); // no template — must be skipped

        ExecuteBackfill();

        var bindings = GetAllBindings();
        bindings.Should().HaveCount(2, "one binding per project that had a template");
        bindings.Should().ContainSingle(b => b.ProjectId == p1.ToString() && b.TemplateId == t1.ToString());
        bindings.Should().ContainSingle(b => b.ProjectId == p2.ToString() && b.TemplateId == t2.ToString());
    }

    [Fact]
    public void Backfill_ThreeProjectsAllWithTemplate_CreatesThreeBindings()
    {
        var t = SeedTemplate();
        SeedProject(t);
        SeedProject(t);
        SeedProject(t);

        ExecuteBackfill();

        CountBindings().Should().Be(3, "each of the three projects gets exactly one binding");
    }

    [Fact]
    public void Backfill_GeneratedBinding_HasValidGuidId()
    {
        SeedProject(SeedTemplate());

        ExecuteBackfill();

        var bindings = GetAllBindings();
        bindings.Should().HaveCount(1);
        Guid.TryParse(bindings[0].Id, out _).Should().BeTrue(
            "the UUID generated by randomblob() must be parseable as a GUID");
    }

    [Fact]
    public void Backfill_GeneratedBinding_TimestampsAreUnixMilliseconds()
    {
        SeedProject(SeedTemplate());

        ExecuteBackfill();

        var b = GetAllBindings()[0];
        // Unix ms for any date past 2024 is well above 1.7 trillion
        b.CreatedAt.Should().BeGreaterThan(1_700_000_000_000L,
            "CreatedAt must be stored as Unix milliseconds, not seconds or a Julian day offset");
        b.UpdatedAt.Should().BeGreaterThan(1_700_000_000_000L,
            "UpdatedAt must be stored as Unix milliseconds");
    }

    // ── PrepareAsync: migrated binding renders correct title ──────────────────

    [Fact]
    public async Task PrepareAsync_WithMigratedBinding_RendersCorrectTitle()
    {
        using var conn = new SqliteConnection("Data Source=:memory:");
        conn.Open();
        using var db = BuildDbContext(conn);

        var (releaseId, projectName) = await SeedPostMigrationAsync(
            db,
            titleTemplate: "{{project.name}} {{version}} — Release Notes",
            version: "1.31.0");

        var result = await BuildRenderService(db).PrepareAsync(releaseId, new PreparePageRequest(null, null));

        result.Pages.Should().HaveCount(1);
        result.Pages[0].Title.Should().Be($"{projectName} 1.31.0 — Release Notes",
            "PrepareAsync must render the migrated title template with the correct project name and version");
    }

    [Fact]
    public async Task PrepareAsync_ThreeProjectsWithMigratedBindings_EachRendersCorrectTitle()
    {
        using var conn = new SqliteConnection("Data Source=:memory:");
        conn.Open();
        using var db = BuildDbContext(conn);

        const string titleTemplate = "{{project.name}} {{version}} — Release Notes";

        var (rid1, name1) = await SeedPostMigrationAsync(db, titleTemplate, version: "2.0.0");
        var (rid2, name2) = await SeedPostMigrationAsync(db, titleTemplate, version: "3.1.4");
        var (rid3, name3) = await SeedPostMigrationAsync(db, titleTemplate, version: "1.0.0");

        var svc = BuildRenderService(db);

        var r1 = await svc.PrepareAsync(rid1, new PreparePageRequest(null, null));
        var r2 = await svc.PrepareAsync(rid2, new PreparePageRequest(null, null));
        var r3 = await svc.PrepareAsync(rid3, new PreparePageRequest(null, null));

        r1.Pages[0].Title.Should().Be($"{name1} 2.0.0 — Release Notes");
        r2.Pages[0].Title.Should().Be($"{name2} 3.1.4 — Release Notes");
        r3.Pages[0].Title.Should().Be($"{name3} 1.0.0 — Release Notes");
    }

    // ── Pre-migration schema & seed helpers ──────────────────────────────────

    private void CreatePreMigrationSchema()
    {
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = @"
CREATE TABLE ReleaseNoteTemplates (
    Id TEXT PRIMARY KEY NOT NULL,
    Name TEXT NOT NULL,
    ContentTemplate TEXT NOT NULL,
    IsDefault INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE Projects (
    Id TEXT PRIMARY KEY NOT NULL,
    Name TEXT NOT NULL,
    ReleaseNoteTemplateId TEXT REFERENCES ReleaseNoteTemplates(Id)
);
CREATE TABLE TemplateBindings (
    Id TEXT PRIMARY KEY NOT NULL,
    ProjectId TEXT NOT NULL REFERENCES Projects(Id),
    TemplateId TEXT NOT NULL REFERENCES ReleaseNoteTemplates(Id),
    Kind TEXT NOT NULL,
    PageTitleTemplate TEXT NOT NULL,
    ParentPageId TEXT,
    LinkFromReleaseNotes INTEGER NOT NULL DEFAULT 0,
    SortOrder INTEGER NOT NULL DEFAULT 0,
    CreatedAt INTEGER NOT NULL,
    UpdatedAt INTEGER NOT NULL
);";
        cmd.ExecuteNonQuery();
    }

    private Guid SeedTemplate(string name = "Release Template")
    {
        var id = Guid.NewGuid();
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = "INSERT INTO ReleaseNoteTemplates (Id, Name, ContentTemplate, IsDefault) VALUES ($id, $name, '# Release Notes', 0)";
        cmd.Parameters.AddWithValue("$id", id.ToString());
        cmd.Parameters.AddWithValue("$name", name);
        cmd.ExecuteNonQuery();
        return id;
    }

    private Guid SeedProject(Guid? templateId)
    {
        var id = Guid.NewGuid();
        using var cmd = _connection.CreateCommand();
        if (templateId.HasValue)
        {
            cmd.CommandText = "INSERT INTO Projects (Id, Name, ReleaseNoteTemplateId) VALUES ($id, $name, $tid)";
            cmd.Parameters.AddWithValue("$id", id.ToString());
            cmd.Parameters.AddWithValue("$name", $"Proj-{id:N}");
            cmd.Parameters.AddWithValue("$tid", templateId.Value.ToString());
        }
        else
        {
            cmd.CommandText = "INSERT INTO Projects (Id, Name) VALUES ($id, $name)";
            cmd.Parameters.AddWithValue("$id", id.ToString());
            cmd.Parameters.AddWithValue("$name", $"Proj-{id:N}");
        }
        cmd.ExecuteNonQuery();
        return id;
    }

    private void ExecuteBackfill()
    {
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = BackfillSql;
        cmd.ExecuteNonQuery();
    }

    private int CountBindings()
    {
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = "SELECT COUNT(*) FROM TemplateBindings";
        return Convert.ToInt32(cmd.ExecuteScalar());
    }

    private record BindingRow(
        string Id,
        string ProjectId,
        string TemplateId,
        string Kind,
        string PageTitleTemplate,
        int SortOrder,
        int LinkFromReleaseNotes,
        string? ParentPageId,
        long CreatedAt,
        long UpdatedAt);

    private List<BindingRow> GetAllBindings()
    {
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = @"
SELECT Id, ProjectId, TemplateId, Kind, PageTitleTemplate,
       SortOrder, LinkFromReleaseNotes, ParentPageId, CreatedAt, UpdatedAt
FROM TemplateBindings";
        using var reader = cmd.ExecuteReader();
        var result = new List<BindingRow>();
        while (reader.Read())
        {
            result.Add(new BindingRow(
                reader.GetString(0),
                reader.GetString(1),
                reader.GetString(2),
                reader.GetString(3),
                reader.GetString(4),
                reader.GetInt32(5),
                reader.GetInt32(6),
                reader.IsDBNull(7) ? null : reader.GetString(7),
                reader.GetInt64(8),
                reader.GetInt64(9)));
        }
        return result;
    }

    // ── Post-migration seed & service helpers ─────────────────────────────────

    private static AppDbContext BuildDbContext(SqliteConnection conn)
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseSqlite(conn)
            .Options;
        var db = new AppDbContext(options);
        db.Database.EnsureCreated();
        return db;
    }

    private static ReleaseRenderService BuildRenderService(AppDbContext db)
    {
        var recorder = new MissingTokenRecorder();
        var hbs = HandlebarsFactory.Create(recorder);
        return new ReleaseRenderService(
            db,
            hbs,
            recorder,
            new Mock<IConfluencePublisher>().Object,
            new EphemeralDataProtectionProvider(),
            NullLogger<ReleaseRenderService>.Instance);
    }

    private static async Task<(Guid releaseId, string projectName)> SeedPostMigrationAsync(
        AppDbContext db,
        string titleTemplate,
        string? projectName = null,
        string version = "1.5.0")
    {
        projectName ??= $"Project-{Guid.NewGuid():N}";

        var user = new User
        {
            Id = Guid.NewGuid(),
            Email = $"u{Guid.NewGuid():N}@t.com",
            PasswordHash = "h",
            Role = Role.Admin,
            IsActive = true,
            CreatedAt = DateTimeOffset.UtcNow,
        };
        db.Users.Add(user);

        var project = new Project
        {
            Id = Guid.NewGuid(),
            Name = projectName,
            Color = "#000000",
            JiraProjectKeys = "[]",
            ConfluenceSpaceKey = "SPACE",
            ConfluenceParentPageId = "99999",
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow,
        };
        db.Projects.Add(project);

        var template = new ReleaseNoteTemplate
        {
            Id = Guid.NewGuid(),
            Name = $"Tmpl-{Guid.NewGuid():N}",
            ContentTemplate = "Release body for {{project.name}}",
            IsDefault = false,
        };
        db.ReleaseNoteTemplates.Add(template);

        // Binding seeded to match what the migration backfill produces
        var binding = new ProjectTemplateBinding
        {
            Id = Guid.NewGuid(),
            ProjectId = project.Id,
            TemplateId = template.Id,
            Kind = TemplateBindingKind.ReleaseNotes,
            PageTitleTemplate = titleTemplate,
            SortOrder = 0,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow,
        };
        db.TemplateBindings.Add(binding);

        var release = new Release
        {
            Id = Guid.NewGuid(),
            ProjectId = project.Id,
            Name = $"v{version}",
            Version = version,
            Status = ReleaseStatus.Draft,
            GeneratedNotesMarkdown = string.Empty,
            CreatedByUserId = user.Id,
            CreatedAt = DateTimeOffset.UtcNow,
        };
        db.Releases.Add(release);

        await db.SaveChangesAsync();
        return (release.Id, projectName);
    }
}
