// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepoManager.Infrastructure.Persistence;

#nullable disable

namespace RepoManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("RepoManager.Domain.Aggregates.ProjectSync", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SucceededCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalRepos")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TriggeredByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("Status IN (0, 1)");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("ProjectId", "Status", "StartedAt");

                    b.ToTable("ProjectSyncs");
                });

            modelBuilder.Entity("RepoManager.Domain.Aggregates.RepositorySync", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BreakingChangeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("CommitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContributorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ContributorsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("CurrentStep")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectSyncId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ToCommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TriggeredByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectSyncId");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("RepositoryId", "FromTag", "Status", "StartedAt");

                    b.ToTable("RepositorySyncs");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Commit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CommittedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBreaking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsConventional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("JiraTicketId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortSha")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommittedAt");

                    b.HasIndex("JiraTicketId");

                    b.HasIndex("RepositoryId", "Sha")
                        .IsUnique();

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.ConfluenceConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChecklistTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LastTestStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastTestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfluenceConnections");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.GitProviderConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<long?>("LastSyncedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTestStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GitProviderConnections");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.JiraConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<long?>("LastTestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JiraConnections");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.JiraRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JiraConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraProjectKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraVersionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSyncedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JiraConnectionId", "JiraVersionId")
                        .IsUnique();

                    b.ToTable("JiraReleases");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.JiraTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JiraReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSyncedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JiraReleaseId", "Key")
                        .IsUnique();

                    b.ToTable("JiraTickets");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoCreateFixVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfluenceParentPageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfluenceSpaceKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FixVersionPattern")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JiraConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraProjectKeys")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<bool>("MatchSubtasksToParents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReleaseNoteTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JiraConnectionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ReleaseNoteTemplateId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.ProjectRepository", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("ProjectId", "RepositoryId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("ProjectRepositories");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfluencePageId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfluencePageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditedNotesMarkdown")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedNotesMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.ReleaseNoteTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReleaseNoteTemplates");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.ReleaseReconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("GitOnlyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JiraOnlyCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JiraReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MatchRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RunAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JiraReleaseId");

                    b.HasIndex("ReleaseId")
                        .IsUnique();

                    b.ToTable("ReleaseReconciliations");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.ReleaseRepositoryTag", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CommitCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ReleaseId", "RepositoryId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("ReleaseRepositoryTags");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.RepoJiraComparisonSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommitCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("GitOnlyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitOnlyJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("GitTicketCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InBothCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InBothJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<bool>("JiraFixVersionExists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraFixVersionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("JiraOnlyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JiraOnlyJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("JiraTicketCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MatchRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Supported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnmatchedCommitsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("UnsupportedReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "NextVersion")
                        .IsUnique();

                    b.ToTable("RepoJiraComparisonSnapshots");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GitProviderConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTracked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<long?>("LastSyncedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastViewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestTag")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestTagCommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestTagSetAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LatestTagSetByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsTracked");

                    b.HasIndex("LatestTagSetByUserId");

                    b.HasIndex("GitProviderConnectionId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommitCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContributorCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstCommittedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBreaking")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastCommittedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "FromTag", "ToTag", "TicketId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RefreshTokenExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RepoManager.Domain.Aggregates.ProjectSync", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoManager.Domain.Entities.User", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TriggeredBy");
                });

            modelBuilder.Entity("RepoManager.Domain.Aggregates.RepositorySync", b =>
                {
                    b.HasOne("RepoManager.Domain.Aggregates.ProjectSync", "ProjectSync")
                        .WithMany("RepositorySyncs")
                        .HasForeignKey("ProjectSyncId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RepoManager.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoManager.Domain.Entities.User", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectSync");

                    b.Navigation("Repository");

                    b.Navigation("TriggeredBy");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Commit", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.Repository", "Repository")
                        .WithMany("Commits")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.JiraRelease", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.JiraConnection", "JiraConnection")
                        .WithMany("JiraReleases")
                        .HasForeignKey("JiraConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JiraConnection");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.JiraTicket", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.JiraRelease", "JiraRelease")
                        .WithMany("JiraTickets")
                        .HasForeignKey("JiraReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JiraRelease");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Project", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.JiraConnection", "JiraConnection")
                        .WithMany("Projects")
                        .HasForeignKey("JiraConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RepoManager.Domain.Entities.ReleaseNoteTemplate", "ReleaseNoteTemplate")
                        .WithMany("Projects")
                        .HasForeignKey("ReleaseNoteTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JiraConnection");

                    b.Navigation("ReleaseNoteTemplate");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.ProjectRepository", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.Project", "Project")
                        .WithMany("ProjectRepositories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoManager.Domain.Entities.Repository", "Repository")
                        .WithMany("ProjectRepositories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Release", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RepoManager.Domain.Entities.Project", "Project")
                        .WithMany("Releases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.ReleaseReconciliation", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.JiraRelease", "JiraRelease")
                        .WithMany()
                        .HasForeignKey("JiraReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RepoManager.Domain.Entities.Release", "Release")
                        .WithOne("Reconciliation")
                        .HasForeignKey("RepoManager.Domain.Entities.ReleaseReconciliation", "ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JiraRelease");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.ReleaseRepositoryTag", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.Release", "Release")
                        .WithMany("RepositoryTags")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoManager.Domain.Entities.Repository", "Repository")
                        .WithMany("ReleaseRepositoryTags")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.RepoJiraComparisonSnapshot", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.Repository", "Repository")
                        .WithMany("JiraComparisonSnapshots")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Repository", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.GitProviderConnection", "GitProviderConnection")
                        .WithMany("Repositories")
                        .HasForeignKey("GitProviderConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoManager.Domain.Entities.User", "LatestTagSetBy")
                        .WithMany()
                        .HasForeignKey("LatestTagSetByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GitProviderConnection");

                    b.Navigation("LatestTagSetBy");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("RepoManager.Domain.Entities.Repository", "Repository")
                        .WithMany("Tickets")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoManager.Domain.Aggregates.ProjectSync", b =>
                {
                    b.Navigation("RepositorySyncs");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.GitProviderConnection", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.JiraConnection", b =>
                {
                    b.Navigation("JiraReleases");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.JiraRelease", b =>
                {
                    b.Navigation("JiraTickets");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectRepositories");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Release", b =>
                {
                    b.Navigation("Reconciliation");

                    b.Navigation("RepositoryTags");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.ReleaseNoteTemplate", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("RepoManager.Domain.Entities.Repository", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("JiraComparisonSnapshots");

                    b.Navigation("ProjectRepositories");

                    b.Navigation("ReleaseRepositoryTags");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
